---
language: generic

sudo: false

services:
  - docker

before_script:
  - npm install -g snyk

script:
  - docker build -t ushi/mailman .

before_deploy:
  - if test -n "${TRAVIS_TAG}"; then
      docker tag ushi/mailman "ushi/mailman:${TRAVIS_TAG}";
    else
      docker tag ushi/mailman "ushi/mailman:latest";
    fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push "ushi/mailman:${TRAVIS_TAG}"
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: docker push "ushi/mailman:latest"
    on:
      branch: master
